language: python
python: 3.5
cache: pip
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=flake8
install:
  - travis_retry pip install tox
script:
  - travis_retry tox
